package com.cesar31.sumaparser.view;

import com.cesar31.sumaparser.Main.Control;
import java.awt.Event;
import javax.swing.Action;
import javax.swing.KeyStroke;
import javax.swing.text.DefaultEditorKit;

/**
 *
 * @author cesar31
 */
public class MainView extends javax.swing.JFrame {

    // Para control de lineas
    private LineNumber num;
    private Control control;

    public MainView(Control control) {
        initComponents();
        initLineNumber();
        textMainSetActions();
        this.control = control;
    }

    /**
     * Numero de linea para JTextArea
     */
    private void initLineNumber() {
        // Editor para usuario
        num = new LineNumber(textMain);
        scrollText.setRowHeaderView(num);
    }

    /**
     * Acciones de cortar, copiar y pegar en textMain
     */
    private void textMainSetActions() {
        Action cut = textMain.getActionMap().get(DefaultEditorKit.cutAction);
        cut.putValue(Action.NAME, "Cortar");
        cut.putValue(Action.ACCELERATOR_KEY, KeyStroke.getAWTKeyStroke('X', Event.CTRL_MASK));

        Action copy = textMain.getActionMap().get(DefaultEditorKit.copyAction);
        copy.putValue(Action.NAME, "Copiar");
        copy.putValue(Action.ACCELERATOR_KEY, KeyStroke.getAWTKeyStroke('C', Event.CTRL_MASK));

        Action paste = textMain.getActionMap().get(DefaultEditorKit.pasteAction);
        paste.putValue(Action.NAME, "Pegar");
        paste.putValue(Action.ACCELERATOR_KEY, KeyStroke.getAWTKeyStroke('V', Event.CTRL_MASK));

        // Agregar a los menu 
        ItemCut.setAction(cut);
        ItemCopy.setAction(copy);
        ItemPaste.setAction(paste);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myTabbedPane = new javax.swing.JTabbedPane();
        mainPanel = new javax.swing.JPanel();
        scrollText = new javax.swing.JScrollPane();
        textMain = new javax.swing.JTextArea();
        btnRequest = new javax.swing.JButton();
        labelResult = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menu1 = new javax.swing.JMenu();
        itemNew = new javax.swing.JMenuItem();
        itemOpen = new javax.swing.JMenuItem();
        itemSave = new javax.swing.JMenuItem();
        itemSaveAs = new javax.swing.JMenuItem();
        itemExit = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JMenu();
        ItemCut = new javax.swing.JMenuItem();
        ItemCopy = new javax.swing.JMenuItem();
        ItemPaste = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(36, 27, 47));
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setPreferredSize(new java.awt.Dimension(1024, 720));
        setResizable(false);

        myTabbedPane.setBackground(new java.awt.Color(23, 21, 32));
        myTabbedPane.setForeground(new java.awt.Color(0, 0, 0));
        myTabbedPane.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        mainPanel.setBackground(new java.awt.Color(23, 21, 32));
        mainPanel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(1024, 688));
        mainPanel.setName(""); // NOI18N

        textMain.setBackground(new java.awt.Color(42, 33, 57));
        textMain.setColumns(20);
        textMain.setFont(new java.awt.Font("Hack", 0, 16)); // NOI18N
        textMain.setForeground(new java.awt.Color(255, 255, 255));
        textMain.setRows(5);
        textMain.setTabSize(4);
        textMain.setCaretColor(new java.awt.Color(255, 255, 255));
        textMain.setMargin(new java.awt.Insets(10, 10, 10, 10));
        textMain.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                textMainCaretUpdate(evt);
            }
        });
        scrollText.setViewportView(textMain);

        btnRequest.setBackground(new java.awt.Color(42, 33, 57));
        btnRequest.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnRequest.setText("Evaluar");
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        labelResult.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        labelResult.setForeground(new java.awt.Color(255, 255, 255));
        labelResult.setText("El resultado es: ");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollText, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(btnRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(scrollText, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRequest)
                    .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        myTabbedPane.addTab("Peticiones", mainPanel);

        menuBar.setBackground(new java.awt.Color(36, 27, 47));
        menuBar.setForeground(new java.awt.Color(255, 255, 255));
        menuBar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        menuBar.setMinimumSize(new java.awt.Dimension(70, 32));
        menuBar.setPreferredSize(new java.awt.Dimension(70, 32));

        menu1.setBackground(new java.awt.Color(36, 27, 47));
        menu1.setForeground(new java.awt.Color(255, 255, 255));
        menu1.setText("File");
        menu1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        itemNew.setBackground(new java.awt.Color(36, 27, 47));
        itemNew.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        itemNew.setForeground(new java.awt.Color(255, 255, 255));
        itemNew.setText("Nuevo");
        itemNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNewActionPerformed(evt);
            }
        });
        menu1.add(itemNew);

        itemOpen.setBackground(new java.awt.Color(36, 27, 47));
        itemOpen.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        itemOpen.setForeground(new java.awt.Color(255, 255, 255));
        itemOpen.setText("Abrir...");
        itemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOpenActionPerformed(evt);
            }
        });
        menu1.add(itemOpen);

        itemSave.setBackground(new java.awt.Color(36, 27, 47));
        itemSave.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        itemSave.setForeground(new java.awt.Color(255, 255, 255));
        itemSave.setText("Guardar");
        itemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveActionPerformed(evt);
            }
        });
        menu1.add(itemSave);

        itemSaveAs.setBackground(new java.awt.Color(36, 27, 47));
        itemSaveAs.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        itemSaveAs.setForeground(new java.awt.Color(255, 255, 255));
        itemSaveAs.setText("Guardar como...");
        itemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSaveAsActionPerformed(evt);
            }
        });
        menu1.add(itemSaveAs);

        itemExit.setBackground(new java.awt.Color(36, 27, 47));
        itemExit.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        itemExit.setForeground(new java.awt.Color(255, 255, 255));
        itemExit.setText("Exit");
        itemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExitActionPerformed(evt);
            }
        });
        menu1.add(itemExit);

        menuBar.add(menu1);

        menu2.setBackground(new java.awt.Color(36, 27, 47));
        menu2.setForeground(new java.awt.Color(255, 255, 255));
        menu2.setText("Edit");
        menu2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        ItemCut.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemCut.setBackground(new java.awt.Color(36, 27, 47));
        ItemCut.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ItemCut.setForeground(new java.awt.Color(255, 255, 255));
        ItemCut.setText("Cortar");
        menu2.add(ItemCut);

        ItemCopy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemCopy.setBackground(new java.awt.Color(36, 27, 47));
        ItemCopy.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ItemCopy.setForeground(new java.awt.Color(255, 255, 255));
        ItemCopy.setText("Copiar");
        menu2.add(ItemCopy);

        ItemPaste.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ItemPaste.setBackground(new java.awt.Color(36, 27, 47));
        ItemPaste.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        ItemPaste.setForeground(new java.awt.Color(255, 255, 255));
        ItemPaste.setText("Pegar");
        menu2.add(ItemPaste);

        menuBar.add(menu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myTabbedPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento para cerrar el programa
     *
     * @param evt
     */
    private void itemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_itemExitActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        String value = textMain.getText();
        Integer result = this.control.parseInput(value);
        labelResult.setText("El resultado es: " + result);
    }//GEN-LAST:event_btnRequestActionPerformed

    /**
     * Obtener informacion de linea y columna
     *
     * @param evt
     */
    private void textMainCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_textMainCaretUpdate

    }//GEN-LAST:event_textMainCaretUpdate

    private void itemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOpenActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_itemOpenActionPerformed

    private void itemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveAsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSaveAsActionPerformed

    private void itemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSaveActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_itemSaveActionPerformed

    private void itemNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNewActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemCopy;
    private javax.swing.JMenuItem ItemCut;
    private javax.swing.JMenuItem ItemPaste;
    private javax.swing.JButton btnRequest;
    private javax.swing.JMenuItem itemExit;
    private javax.swing.JMenuItem itemNew;
    private javax.swing.JMenuItem itemOpen;
    private javax.swing.JMenuItem itemSave;
    private javax.swing.JMenuItem itemSaveAs;
    private javax.swing.JLabel labelResult;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenu menu1;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JTabbedPane myTabbedPane;
    private javax.swing.JScrollPane scrollText;
    private javax.swing.JTextArea textMain;
    // End of variables declaration//GEN-END:variables
}
