
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.cesar31.sumaparser.parser;

/** CUP generated class containing symbol constants. */
public class SumaParserSym {
  /* terminals */
  public static final int INTEGER = 2;
  public static final int RPAREN = 6;
  public static final int ERROR = 7;
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int LPAREN = 5;
  public static final int TIMES = 4;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INTEGER",
  "PLUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "ERROR"
  };
}

